### ISSUE TITLE
Polyfill makes container query refer to parent size, not container size

### ISSUE THREAD

**Issue by ilyamerman** [Marshal27/shadow-container-query-polyfill#33]
Hey guys, very happy about this polyfill since web-components are a perfect use-case for container queries! :)

Ran into an observation during development:
[CodeSandbox link](https://codesandbox.io/s/web-components-using-vanilla-js-forked-61pzpd?file=/index.html)

In the example, we have an outer div (red border, 200x200 which we **declare to be our container**) and an inner div (blue border, 100x100), inside it is some text.
The @container css code is set up in such a way that when the red box is shrunk to be smaller than 150px in width, the font-size will be smaller.

### On Chrome:
Works great in Chrome due to native container queries support:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/18516271/205023317-7e89a66a-176a-479e-9ed5-88b510bde02c.png">
<img width="143" alt="image" src="https://user-images.githubusercontent.com/18516271/205023352-2b8fbe9f-d674-4558-93e1-8446d4933c09.png">

### On Firefox
But with the polyfill on Firefox (which as we know doesn't have native container query support in any version), the text is always shrunk to be the smaller size:
<img width="182" alt="image" src="https://user-images.githubusercontent.com/18516271/205023533-2e11bc0e-873e-4ad3-8217-c6d30419f80d.png">

Although when resizing the **blue** box to be more than 150px, the text is actually getting larger:
<img width="187" alt="image" src="https://user-images.githubusercontent.com/18516271/205023661-357620a3-c222-4ac4-b4fd-991a3012c897.png">

It looks like the parent div is always considered to be the container, even if it doesn't have the `container-type` css attribute.

Also, the computed css variables like `cqw` and `cqh` are computed according to the parent and not the declared container:
<img width="669" alt="image" src="https://user-images.githubusercontent.com/18516271/205024326-ad345fcd-4f93-4518-97f2-38019c68f5a3.png">

(I would expect `cqw` to be 2px here since `cqw` is 1% of the container size which is 200px)

Would love to help, just not sure how to get started setting up the project.
Thanks!

**Comment by Marshal27** [comment]
@ilyamerman Thank you for reporting this issue.

The Shadow DOM feature was originally scoped for the native `GoogleChromeLabs/container-query-polyfill` repo, but, it did not make it before the repo went in to maintenance mode. This fork was created at the recommendation of `DevKnoll` (here [PR 57](https://github.com/GoogleChromeLabs/container-query-polyfill/pull/57#issuecomment-1309241441)) as a place for the Shadow DOM feature to be available which makes me a team of one on this work.

The detail you provided above is much appreciated and was instrumental in helping me spot the issue. 

I have outlined the specific details regarding the root issue in #34 if you are interested in taking a closer look.

Regarding contributions, it's not something I have thought about up to this point, but would certainly be open to it... very possible in the near future and likely just a matter of adding details on contributing in the readme, however, this will be driven by issue volume and request for enhancements etc... it is too early to tell at this point how much volume, if any, there may be.

Thank you again for taking the time to report your findings and please let me know if the new patch resolves your issue.

**Comment by ilyamerman** [comment]
@Marshal27 thank you so much for putting time into this!
This does resolve the issue.

There's a little issue with multiple instances, it looks like the new stylesheet is appended only for the last declared component

Sandbox link: https://codesandbox.io/s/web-components-using-vanilla-js-forked-ixku98
Image (from Firefox)
<img width="255" alt="image" src="https://user-images.githubusercontent.com/18516271/206862265-213affbd-0d14-4a7a-9ea1-1f693daf7fad.png">

In the DOM the new style tag that fixes the issue exists only in the last component
<img width="480" alt="image" src="https://user-images.githubusercontent.com/18516271/206862399-fb4e46b3-bc5b-457b-a0fe-76ac11be3a7b.png">

**Comment by Marshal27** [comment]
@ilyamerman give #37 a shot.
