### ISSUE TITLE
Orientation queries support?

### ISSUE THREAD

**Issue by akbar-idwise** [Marshal27/shadow-container-query-polyfill#39]
Are queries like these supported?
```
@container (orientation: portrait){

}
```

**Comment by akbar-idwise** [comment]
They are actually but i think orientation is calculated incorrectly i.e for landscape its recognising it as portrait and vice versa

**Comment by Marshal27** [comment]
The classification logic comes from the source repo this repo was forked from, and is not something I wrote. 

It was written by someone on the Chrome Labs team. The `GoogleChromeLabs/container-query-polyfill` repo is in maintenance mode, and, if they were to apply a patch, I could pull that change set in over here to add it to the shadow dom support repo.

If you can provide me a stackblitz (or something similar) demonstrating the issue, I could take a look and patch it over here to provide support sooner vs waiting on them and consuming it here.

This is the evaluation logic for orientation and for the most part appears correct, except for maybe considering a `square` as a `portrait`... is that possibly what you are seeing, a `square` being considered a `portrait`?
```js
height >= width ? 'portrait' : 'landscape'
```

**Comment by meduzen** [comment]
> ```js
> height >= width ? 'portrait' : 'landscape'
> ```

FYI this is also how the [spec defines it](https://drafts.csswg.org/mediaqueries/#orientation) (a square viewport is `portrait`), so the condition is correct.

**Comment by Marshal27** [comment]
> > ```js
> > height >= width ? 'portrait' : 'landscape'
> > ```
> 
> FYI this is also how the [spec defines it](https://drafts.csswg.org/mediaqueries/#orientation) (a square viewport is `portrait`), so the condition is correct.

That is good to know.

**Comment by Marshal27** [comment]
Here is a `stackblitz` demo for the `orientation` selector using `shadow-container-query-polyfill`, and it does not appear to be miss calculating `portrait` vs `landscape` and is working according to spec.

Based on the demo I am going to close this issue as resolved. If you believe this to still be a problem, please fork/adjust this stackblitz to replicate the issue you are seeing and I will take a closer look.

https://stackblitz.com/edit/shadow-container-query-polyfill-orientation-demo?file=index.html
