### ISSUE TITLE
Do not throw ResizeObserver loop limit exceeded errors

### ISSUE THREAD

**Issue by Maximaximum** [Marshal27/shadow-container-query-polyfill#40]
Even though the `README.md` explicitly mentions that the `ResizeObserver loop limits exceeded error` can be ignored, this does not seem to be a proper behavior. The error should not be thrown at all instead. This can be easily achieved by wrapping the `ResizeObserver` constructor callback with a `requestAnimationFrame()` call.

The problem with current implementation is that we have a global error handler. The handler ensures that the app fails on any unhandled exception, and sends the error to the Sentry endpoint so that we can monitor all the unhandled errors that occur while using the app.

While in the handler we could check if an error message contains a “ResizeObserver” string, or has exactly a specific error message string, and ignore it in such case, this is not a best practice scalable and manageable solution. 

Besides, we might want to be informed on `ResizeObserver` errors that occur in other places in the app, but not in the container query polyfill.

**Comment by Marshal27** [comment]
@Maximaximum Ultimately the `ResizeObserver` implementation, along with the readme, came from the source repo this was forked from. I simply added shadow DOM support to the polyfill, which was unfortunately not merged in before the original repo went in to maintenance mode, and this fork was created at the recommendation of `devknoll` on the `GoogleChromeLabs` team.

With that said, I appreciate you pointing this out, and I will take a closer look.

**Comment by Marshal27** [comment]
Adding this here for posterity. 

Avoid ResizeObserver loop limit exceeded. The issues surfaces on Chrome version >=64.
> since ResizeObserver seems to be firing the callback immediately after observe() is called, this causes an infinite loop.

Reference: https://github.com/WICG/resize-observer/issues/38


Eventually the error may be turned into a warning via [w3c Issue#5023](https://github.com/w3c/csswg-drafts/issues/5023).. in lieu of having that as a viable solution, I am working on the recommended fix mentioned by the OP.

**Comment by Marshal27** [comment]
@Maximaximum  Please run v1.1.8 through its paces, and feel free to re-open this issue if the problem has not been resolved.
